import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react';

const defaultEndpoint = "https://rickandmortyapi.com/api/character/";

export async function getServerSideProps() {
  const res = await fetch(defaultEndpoint);
  const data = await res.json();

  return {
    props: {
      data,
    },
  };
}

export default function Home({data}) {
 const { info, results: defaultResults =[]} = data;
 const [results, setResults] = useState(defaultResults)
 const [page, updatePage] = useState({
   ...info,
   current: defaultEndpoint
 })
  return (
    <div className={styles.container}>
      <Head>
        <title>Wubba wubba wubba</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         <a>Wubba wubba wubba</a>
        </h1>

        <p className={styles.description}>
       Rick and Morty wiki
          <code className={styles.code}>pages/index.js</code>
        </p>

        <ul className={styles.grid}>
          {results.map(result => {
            const {id, name,image } =result;
           
            return (  <li className={styles.card} key={id}>
              <a href="https://nextjs.org/docs" >
                <img src={image} alt={`${name}`}></img>
                <h2>{name}</h2>
              </a>
              </li>
              )
          })}
        
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
